language: node_js
node_js: stable
install:
  - yarn install
script:
      - yarn blog:build
after_script:
  - cd dist
  - git init
  - git config user.name "Amazing"
  - git config user.email "804721028@qq.com"
  - git add .
  - git commit -m ":robot:Deploy blog by Travis CI"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/AmazingMoon/amazingmoon.github.io.git